name: Seat Count
author: Austen Stone
description: Count the remaining seats in your GitHub plan.
branding:
  icon: "percent"
  color: "orange"

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  org:
    description: The org to use for the action
    default: ${{ github.event.organization.login }}
    required: false

outputs:
  filled_seats:
    description: The number of filled seats
  seats:
    description: The total number of seats
  percentage:
    description: The percentage of total seats used
  remaining:
    description: The number of remaining seats
  name:
    description: The name of the plan
  space:
    description: The package space remaining
  private_repos:
    description: The number of private repos

runs:
  using: "node16"
  main: "dist/index.js"
