name: Print
permissions: {}
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  seats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: seats
        with:
          org: octodemo
          github-token: ${{secrets.TOKEN}}
    outputs:
      percentage: ${{steps.seats.outputs.percentage}}
      remaining: ${{steps.seats.outputs.remaining}}
  print:
    needs: [seats]
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{needs.seats.outputs.percentage}}% of seats used"
      - run: echo "${{needs.seats.outputs.remaining}} seats remaining"
  more-than-50:
    needs: [seats]
    if: needs.seats.outputs.percentage > 50
    runs-on: ubuntu-latest
    steps:
      - run: echo More than 50% of seats used.
  less-than-50:
    needs: [seats]
    if: needs.seats.outputs.percentage < 50
    runs-on: ubuntu-latest
    steps:
      - run: echo Less than 50% of seats used.
